/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CharacterJava;

/**
 *
 * @author carlos
 */
public class Charact extends javax.swing.JFrame {

    /**
     * Creates new form Charact
     */
    public Charact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCampo = new javax.swing.JTextField();
        jBtnIsDigit = new javax.swing.JButton();
        jBtnIsLetter = new javax.swing.JButton();
        jBtnIsDigitOrLetter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresa 1 o mas caracteres");

        jBtnIsDigit.setText("IsDigit");
        jBtnIsDigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIsDigitActionPerformed(evt);
            }
        });

        jBtnIsLetter.setText("IsLetter");
        jBtnIsLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIsLetterActionPerformed(evt);
            }
        });

        jBtnIsDigitOrLetter.setText("IsDIgit or IsLetter");
        jBtnIsDigitOrLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIsDigitOrLetterActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtnIsDigit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnIsLetter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnIsDigitOrLetter, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIsDigit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnIsLetter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnIsDigitOrLetter)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIsDigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIsDigitActionPerformed
     String value = jTxtCampo.getText();
     jTextArea1.setText("");
	
	for (int i = 0; i < value.length(); i++) {
	    char c = value.charAt(i);

	    if (Character.isDigit(c)) {
                jTextArea1.append(String.valueOf(c)+ " = IS DIGIT"+ '\n');
		
	    } else if (Character.isLetter(c)) {
               jTextArea1.append(String.valueOf(c)+ " = FALSE"+ '\n');
            }
	}
    }//GEN-LAST:event_jBtnIsDigitActionPerformed

    private void jBtnIsLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIsLetterActionPerformed
        String value = jTxtCampo.getText();
        jTextArea1.setText("");
	
	for (int i = 0; i < value.length(); i++) {
	    char c = value.charAt(i);

	    if (Character.isDigit(c)) {
                jTextArea1.append(String.valueOf(c)+ " = FALSE"+ '\n');
		
	    } else if (Character.isLetter(c)) {
               jTextArea1.append(String.valueOf(c)+ " = IS LETTER"+ '\n');
            }
	}
    }//GEN-LAST:event_jBtnIsLetterActionPerformed

    private void jBtnIsDigitOrLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIsDigitOrLetterActionPerformed
     String value = jTxtCampo.getText();
        jTextArea1.setText("");
	
	for (int i = 0; i < value.length(); i++) {
	    char c = value.charAt(i);

	    if (Character.isDigit(c)) {
                jTextArea1.append(String.valueOf(c)+ " = IS DIGIT"+ '\n');
		
	    } else if (Character.isLetter(c)) {
               jTextArea1.append(String.valueOf(c)+ " = IS LETTER"+ '\n');
            }
	}
    }//GEN-LAST:event_jBtnIsDigitOrLetterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Charact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Charact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Charact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Charact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Charact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIsDigit;
    private javax.swing.JButton jBtnIsDigitOrLetter;
    private javax.swing.JButton jBtnIsLetter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtCampo;
    // End of variables declaration//GEN-END:variables
}
